import type { Faction, MetroLine, Station, SupportedLanguage } from "@/types/metro";
import { interfaceCopy, localizedText } from "@/lib/metro/i18n";

type StationPanelProps = { station?: Station; faction?: Faction; connections: Station[]; lines: MetroLine[]; language: SupportedLanguage; onClose: () => void; onRoute: () => void };

export function StationPanel({ station, faction, connections, lines, language, onClose, onRoute }: StationPanelProps) {
  if (!station) return null;
  const name = localizedText(station.name, language);
  const status = { active: language === "es" ? "Activa" : "Active", abandoned: language === "es" ? "Abandonada" : "Abandoned", independent: language === "es" ? "Independiente" : "Independent", captured: language === "es" ? "Capturada" : "Captured", destroyed: language === "es" ? "Destruida" : "Destroyed" }[station.status];
  return <aside className="station-panel" aria-label={language === "es" ? "Detalles de estación" : "Station details"}><div className="panel-kicker"><span>{localizedText(interfaceCopy.fieldRecord, language)}</span><button className="icon-button" onClick={onClose} aria-label={language === "es" ? "Cerrar panel" : "Close station panel"}>×</button></div><div className="station-heading"><span className="station-status-dot" style={{ backgroundColor: faction?.color ?? "#9aa0a8" }} /><div><h2>{name}</h2><p>{faction ? localizedText(faction.name, language) : language === "es" ? "Independiente" : "Independent"}</p></div></div><div className="panel-rule" /><div className="detail-grid"><div><span className="detail-label">{localizedText(interfaceCopy.status, language)}</span><strong className={`status-${station.status}`}>{status}</strong></div><div><span className="detail-label">{localizedText(interfaceCopy.population, language)}</span><strong>{station.population ? station.population.toLocaleString(language === "es" ? "es-ES" : "en-US") : "—"}</strong></div></div><div className="detail-block"><span className="detail-label">{localizedText(interfaceCopy.lines, language)}</span><div className="line-pills">{station.lineIds.map((lineId) => <span key={lineId}>{localizedText(lines.find((line) => line.id === lineId)?.name, language)}</span>)}</div></div><div className="detail-block"><span className="detail-label">{localizedText(interfaceCopy.connectedStations, language)}</span><ul className="connection-list">{connections.length ? connections.map((connection) => <li key={connection.id}>{localizedText(connection.name, language)}<span>↗</span></li>) : <li className="muted">{language === "es" ? "Sin conexiones mapeadas" : "No mapped connections"}</li>}</ul></div><p className="station-description">{localizedText(station.description, language)}</p><button className="route-button" onClick={onRoute}>{localizedText(interfaceCopy.setOrigin, language)}</button></aside>;
}
